// v0 scaffold for: No AI image analysis / computer-aided diagnosis
// Generated by batch_00 audit gaps. Persists to lazy `gap_features` table when DB available.
// TODO: configure credentials
const express = require('express');
const router = express.Router();
const FEATURE_TITLE = "No AI image analysis / computer-aided diagnosis";
let authMiddleware = null;
try {
  authMiddleware = require('../middleware/auth');
} catch (e) {
  authMiddleware = null;
}
if (authMiddleware) {
  // Some projects export the middleware directly; others as { authenticateToken }
  const mw = typeof authMiddleware === 'function' ? authMiddleware : (authMiddleware.authenticateToken || authMiddleware.default || null);
  if (mw) router.use(mw);
}

let db = null;
try {
  db = require('../db');
} catch (e) {
  db = null;
}

async function ensureTable() {
  if (!db) return;
  try {
    const sql = `CREATE TABLE IF NOT EXISTS gap_features (
      id SERIAL PRIMARY KEY,
      project TEXT,
      slug TEXT,
      input JSONB,
      output JSONB,
      created_at TIMESTAMP DEFAULT NOW()
    )`;
    if (typeof db.query === 'function') {
      await db.query(sql);
    }
  } catch (err) {
    // best-effort; ignore in v0
  }
}

async function persist(input, output) {
  if (!db) return;
  try {
    await ensureTable();
    if (typeof db.query === 'function') {
      await db.query(
        'INSERT INTO gap_features(project, slug, input, output) VALUES ($1, $2, $3, $4)',
        ['AIassistant', 'ai-image-analysis-computer-aided', JSON.stringify(input), JSON.stringify(output)]
      );
    }
  } catch (err) {
    // ignore
  }
}

async function callOpenRouter(prompt) {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return { stub: true, note: 'OPENROUTER_API_KEY not set. v0 stub response.' };
  }
  try {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: process.env.OPENROUTER_MODEL || 'anthropic/claude-3.5-sonnet',
        messages: [
          { role: 'system', content: `You are an assistant for the feature: ${FEATURE_TITLE}.` },
          { role: 'user', content: prompt },
        ],
      }),
    });
    if (!res.ok) {
      return { error: `OpenRouter HTTP ${res.status}` };
    }
    const json = await res.json();
    return { choices: json?.choices, model: json?.model };
  } catch (err) {
    return { error: err.message };
  }
}

router.get('/health', (req, res) => {
  res.json({ feature: 'ai-image-analysis-computer-aided', status: 'ok', version: 'v0', kind: 'gap' });
});

router.post('/run', async (req, res) => {
  try {
    const input = req.body || {};
    const prompt = typeof input.input === 'string' ? input.input : JSON.stringify(input);
    const aiResult = await callOpenRouter(prompt);
    const output = {
      feature: 'ai-image-analysis-computer-aided',
      title: FEATURE_TITLE,
      receivedKeys: Object.keys(input),
      ai: aiResult,
    };
    persist(input, output).catch(() => {});
    res.json({ success: true, result: output });
  } catch (err) {
    console.error('[gap-ai-image-analysis-computer-aided] error', err);
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
