\if :{?allow_demo_seed}
\else
\echo 'Demo seed disabled; pass -v allow_demo_seed=1 only for an isolated non-production database.'
\quit
\endif

-- Seed Users
INSERT INTO users (email, password, name, role) VALUES
('admin@radiology.com', '$2a$10$t5lUk8VZUEwsyrvNxABSn.3wUFDCK29nCrHerbBJYuiAxsii3KWpi', 'Admin User', 'admin'),
('doctor@radiology.com', '$2a$10$t5lUk8VZUEwsyrvNxABSn.3wUFDCK29nCrHerbBJYuiAxsii3KWpi', 'Dr. Sarah Mitchell', 'radiologist');

-- Seed Patients (15+)
INSERT INTO patients (patient_id, name, date_of_birth, gender, medical_record_number, phone, email, address, insurance_provider, insurance_id, allergies, medical_history) VALUES
('PAT-001', 'James Thompson', '1965-03-15', 'Male', 'MRN-10001', '555-0101', 'james.thompson@email.com', '123 Oak Street, Boston, MA 02101', 'Blue Cross Blue Shield', 'BCBS-88001', 'Penicillin', 'Hypertension, Type 2 Diabetes'),
('PAT-002', 'Maria Garcia', '1978-07-22', 'Female', 'MRN-10002', '555-0102', 'maria.garcia@email.com', '456 Elm Avenue, Cambridge, MA 02139', 'Aetna', 'AET-77002', 'None', 'Asthma, Seasonal allergies'),
('PAT-003', 'Robert Chen', '1952-11-08', 'Male', 'MRN-10003', '555-0103', 'robert.chen@email.com', '789 Pine Road, Brookline, MA 02445', 'United Healthcare', 'UHC-66003', 'Sulfa drugs', 'COPD, Former smoker, Coronary artery disease'),
('PAT-004', 'Emily Johnson', '1990-01-30', 'Female', 'MRN-10004', '555-0104', 'emily.johnson@email.com', '321 Maple Drive, Somerville, MA 02143', 'Cigna', 'CIG-55004', 'Latex', 'Migraine headaches'),
('PAT-005', 'David Williams', '1945-06-17', 'Male', 'MRN-10005', '555-0105', 'david.williams@email.com', '654 Cedar Lane, Newton, MA 02458', 'Medicare', 'MCR-44005', 'Iodine contrast', 'Prostate cancer (remission), Osteoarthritis'),
('PAT-006', 'Sarah Kim', '1983-09-12', 'Female', 'MRN-10006', '555-0106', 'sarah.kim@email.com', '987 Birch Court, Quincy, MA 02169', 'Harvard Pilgrim', 'HP-33006', 'None', 'Breast cancer screening, Family history of breast cancer'),
('PAT-007', 'Michael Brown', '1971-04-25', 'Male', 'MRN-10007', '555-0107', 'michael.brown@email.com', '147 Walnut Street, Medford, MA 02155', 'Blue Cross Blue Shield', 'BCBS-22007', 'Aspirin', 'Lower back pain, Herniated disc L4-L5'),
('PAT-008', 'Jennifer Davis', '1988-12-03', 'Female', 'MRN-10008', '555-0108', 'jennifer.davis@email.com', '258 Spruce Avenue, Arlington, MA 02474', 'Aetna', 'AET-11008', 'None', 'Pregnancy (28 weeks), Gestational diabetes'),
('PAT-009', 'William Martinez', '1960-08-19', 'Male', 'MRN-10009', '555-0109', 'william.martinez@email.com', '369 Ash Boulevard, Waltham, MA 02451', 'United Healthcare', 'UHC-99009', 'Gadolinium', 'Lung nodule surveillance, Former smoker'),
('PAT-010', 'Lisa Anderson', '1975-02-14', 'Female', 'MRN-10010', '555-0110', 'lisa.anderson@email.com', '480 Hickory Place, Lexington, MA 02420', 'Cigna', 'CIG-88010', 'None', 'Multiple sclerosis, On interferon therapy'),
('PAT-011', 'Thomas Wilson', '1958-10-07', 'Male', 'MRN-10011', '555-0111', 'thomas.wilson@email.com', '591 Poplar Way, Needham, MA 02492', 'Medicare', 'MCR-77011', 'Morphine', 'Abdominal aortic aneurysm, Hypertension'),
('PAT-012', 'Angela Taylor', '1995-05-21', 'Female', 'MRN-10012', '555-0112', 'angela.taylor@email.com', '702 Cypress Road, Framingham, MA 01701', 'Harvard Pilgrim', 'HP-66012', 'None', 'ACL tear (right knee), Sports injury'),
('PAT-013', 'Richard Moore', '1948-01-11', 'Male', 'MRN-10013', '555-0113', 'richard.moore@email.com', '813 Sycamore Drive, Dedham, MA 02026', 'Medicare', 'MCR-55013', 'Codeine', 'Pancreatic mass under investigation, Weight loss'),
('PAT-014', 'Patricia Jackson', '1982-07-29', 'Female', 'MRN-10014', '555-0114', 'patricia.jackson@email.com', '924 Magnolia Circle, Wellesley, MA 02481', 'Blue Cross Blue Shield', 'BCBS-44014', 'None', 'Thyroid nodule, Hashimoto thyroiditis'),
('PAT-015', 'Christopher Lee', '1969-03-04', 'Male', 'MRN-10015', '555-0115', 'christopher.lee@email.com', '135 Dogwood Terrace, Natick, MA 01760', 'United Healthcare', 'UHC-33015', 'Shellfish, Iodine', 'Kidney stones, Recurrent UTI'),
('PAT-016', 'Nancy White', '1956-11-26', 'Female', 'MRN-10016', '555-0116', 'nancy.white@email.com', '246 Redwood Lane, Concord, MA 01742', 'Aetna', 'AET-22016', 'None', 'Hip replacement (left), Osteoporosis');

-- Seed Radiologists (15+)
INSERT INTO radiologists (employee_id, name, email, specialization, license_number, years_experience, phone, department, status, certifications) VALUES
('RAD-001', 'Dr. Sarah Mitchell', 'sarah.mitchell@hospital.com', 'Neuroradiology', 'LIC-NR-001', 15, '555-1001', 'Neuroradiology', 'active', 'ABR Board Certified, CAQ Neuroradiology, Fellowship trained'),
('RAD-002', 'Dr. James Park', 'james.park@hospital.com', 'Musculoskeletal Radiology', 'LIC-MS-002', 12, '555-1002', 'Musculoskeletal', 'active', 'ABR Board Certified, CAQ MSK Radiology'),
('RAD-003', 'Dr. Elena Rodriguez', 'elena.rodriguez@hospital.com', 'Chest Radiology', 'LIC-CR-003', 20, '555-1003', 'Thoracic Imaging', 'active', 'ABR Board Certified, Fellowship Thoracic Imaging'),
('RAD-004', 'Dr. Michael Chang', 'michael.chang@hospital.com', 'Abdominal Radiology', 'LIC-AR-004', 10, '555-1004', 'Body Imaging', 'active', 'ABR Board Certified, CAQ Abdominal Radiology'),
('RAD-005', 'Dr. Rebecca Foster', 'rebecca.foster@hospital.com', 'Breast Imaging', 'LIC-BI-005', 18, '555-1005', 'Breast Imaging Center', 'active', 'ABR Board Certified, CAQ Mammography, SBI member'),
('RAD-006', 'Dr. Anthony Russo', 'anthony.russo@hospital.com', 'Interventional Radiology', 'LIC-IR-006', 14, '555-1006', 'Interventional Radiology', 'active', 'ABR Board Certified, CAQ Interventional Radiology'),
('RAD-007', 'Dr. Priya Patel', 'priya.patel@hospital.com', 'Pediatric Radiology', 'LIC-PR-007', 11, '555-1007', 'Pediatric Imaging', 'active', 'ABR Board Certified, CAQ Pediatric Radiology'),
('RAD-008', 'Dr. William Foster', 'william.foster@hospital.com', 'Nuclear Medicine', 'LIC-NM-008', 16, '555-1008', 'Nuclear Medicine', 'active', 'ABR Board Certified, ABNM Certified'),
('RAD-009', 'Dr. Karen Liu', 'karen.liu@hospital.com', 'Cardiac Imaging', 'LIC-CI-009', 9, '555-1009', 'Cardiac Imaging', 'active', 'ABR Board Certified, SCCT Certified, Level III Cardiac CT'),
('RAD-010', 'Dr. Daniel O''Brien', 'daniel.obrien@hospital.com', 'Emergency Radiology', 'LIC-ER-010', 8, '555-1010', 'Emergency Radiology', 'active', 'ABR Board Certified, CAQ Emergency Radiology'),
('RAD-011', 'Dr. Aisha Mohammed', 'aisha.mohammed@hospital.com', 'Neuroradiology', 'LIC-NR-011', 22, '555-1011', 'Neuroradiology', 'active', 'ABR Board Certified, CAQ Neuroradiology, ASNR Fellow'),
('RAD-012', 'Dr. Steven Clark', 'steven.clark@hospital.com', 'Genitourinary Radiology', 'LIC-GU-012', 13, '555-1012', 'Body Imaging', 'active', 'ABR Board Certified, SAR member'),
('RAD-013', 'Dr. Laura Kim', 'laura.kim@hospital.com', 'Head and Neck Radiology', 'LIC-HN-013', 7, '555-1013', 'Head and Neck Imaging', 'active', 'ABR Board Certified, ASHNR member'),
('RAD-014', 'Dr. Robert Singh', 'robert.singh@hospital.com', 'Vascular Radiology', 'LIC-VR-014', 19, '555-1014', 'Vascular Imaging', 'on_leave', 'ABR Board Certified, CAQ Vascular Imaging'),
('RAD-015', 'Dr. Catherine Nguyen', 'catherine.nguyen@hospital.com', 'Chest Radiology', 'LIC-CR-015', 6, '555-1015', 'Thoracic Imaging', 'active', 'ABR Board Certified, STR member'),
('RAD-016', 'Dr. Marcus Johnson', 'marcus.johnson@hospital.com', 'Musculoskeletal Radiology', 'LIC-MS-016', 17, '555-1016', 'Musculoskeletal', 'active', 'ABR Board Certified, CAQ MSK Radiology, SSR Fellow');

-- Seed Radiology Images (16)
INSERT INTO radiology_images (image_id, patient_id, modality, body_part, description, acquisition_date, dicom_status, de_identified, pacs_location, file_size, referring_physician, clinical_indication, status) VALUES
('IMG-001', 1, 'CT', 'Head', 'CT Head without contrast', '2025-12-01 08:30:00', 'stored', false, '/pacs/ct/2025/12/IMG-001', '245 MB', 'Dr. Alan Wright', 'Acute headache, rule out hemorrhage', 'pending'),
('IMG-002', 2, 'MRI', 'Brain', 'MRI Brain with and without contrast', '2025-12-02 09:15:00', 'stored', false, '/pacs/mri/2025/12/IMG-002', '512 MB', 'Dr. Helen Torres', 'Seizure workup, new onset', 'analyzed'),
('IMG-003', 3, 'CT', 'Chest', 'CT Chest with contrast (PE protocol)', '2025-12-03 10:00:00', 'stored', true, '/pacs/ct/2025/12/IMG-003', '380 MB', 'Dr. Peter Adams', 'Shortness of breath, elevated D-dimer', 'reported'),
('IMG-004', 4, 'X-Ray', 'Chest', 'PA and Lateral Chest X-Ray', '2025-12-04 07:45:00', 'stored', false, '/pacs/xray/2025/12/IMG-004', '15 MB', 'Dr. Linda Scott', 'Persistent cough, rule out pneumonia', 'pending'),
('IMG-005', 5, 'MRI', 'Prostate', 'MRI Prostate multiparametric', '2025-12-05 11:30:00', 'stored', true, '/pacs/mri/2025/12/IMG-005', '620 MB', 'Dr. Mark Stevens', 'Elevated PSA, prostate cancer surveillance', 'analyzed'),
('IMG-006', 6, 'Ultrasound', 'Breast', 'Bilateral Breast Ultrasound', '2025-12-06 13:00:00', 'stored', false, '/pacs/us/2025/12/IMG-006', '85 MB', 'Dr. Susan Harper', 'Palpable mass left breast, mammogram BI-RADS 4', 'pending'),
('IMG-007', 7, 'MRI', 'Lumbar Spine', 'MRI Lumbar Spine without contrast', '2025-12-07 14:15:00', 'stored', false, '/pacs/mri/2025/12/IMG-007', '480 MB', 'Dr. Richard Price', 'Chronic low back pain with radiculopathy', 'reported'),
('IMG-008', 8, 'Ultrasound', 'Abdomen', 'OB Ultrasound - 28 week anatomy scan', '2025-12-08 09:30:00', 'stored', false, '/pacs/us/2025/12/IMG-008', '120 MB', 'Dr. Amy Chen', 'Routine 28-week prenatal ultrasound', 'reported'),
('IMG-009', 9, 'CT', 'Chest', 'Low-dose CT Chest (Lung screening)', '2025-12-09 08:00:00', 'stored', true, '/pacs/ct/2025/12/IMG-009', '195 MB', 'Dr. John Miller', 'Lung nodule follow-up, 6-month interval', 'analyzed'),
('IMG-010', 10, 'MRI', 'Brain', 'MRI Brain with contrast (MS protocol)', '2025-12-10 10:45:00', 'stored', false, '/pacs/mri/2025/12/IMG-010', '550 MB', 'Dr. Nancy Green', 'Multiple sclerosis follow-up, new symptoms', 'pending'),
('IMG-011', 11, 'CT', 'Abdomen', 'CT Abdomen and Pelvis with contrast', '2025-12-11 12:00:00', 'stored', false, '/pacs/ct/2025/12/IMG-011', '420 MB', 'Dr. George Baker', 'AAA surveillance, 6-month follow-up', 'analyzed'),
('IMG-012', 12, 'MRI', 'Knee', 'MRI Right Knee without contrast', '2025-12-12 15:30:00', 'stored', false, '/pacs/mri/2025/12/IMG-012', '350 MB', 'Dr. Chris Evans', 'ACL injury evaluation, sports trauma', 'reported'),
('IMG-013', 13, 'CT', 'Abdomen', 'CT Abdomen with contrast (pancreas protocol)', '2025-12-13 08:15:00', 'stored', true, '/pacs/ct/2025/12/IMG-013', '460 MB', 'Dr. Barbara Hill', 'Pancreatic mass characterization, weight loss', 'pending'),
('IMG-014', 14, 'Ultrasound', 'Thyroid', 'Thyroid Ultrasound with Doppler', '2025-12-14 11:00:00', 'stored', false, '/pacs/us/2025/12/IMG-014', '65 MB', 'Dr. Kevin Young', 'Thyroid nodule follow-up, TI-RADS assessment', 'analyzed'),
('IMG-015', 15, 'CT', 'Abdomen', 'CT Abdomen without contrast (renal stone protocol)', '2025-12-15 09:45:00', 'stored', false, '/pacs/ct/2025/12/IMG-015', '290 MB', 'Dr. Dorothy Martin', 'Acute flank pain, suspected nephrolithiasis', 'pending'),
('IMG-016', 16, 'PET', 'Whole Body', 'PET/CT Whole Body (FDG)', '2025-12-16 07:30:00', 'stored', true, '/pacs/pet/2025/12/IMG-016', '850 MB', 'Dr. Frank Lewis', 'Staging workup, newly diagnosed lymphoma', 'analyzed');

-- Seed AI Analyses (16)
INSERT INTO ai_analyses (analysis_id, image_id, analysis_type, findings, confidence_score, areas_of_interest, ai_model, status, reviewed_by, review_notes) VALUES
('ANA-001', 1, 'Hemorrhage Detection', 'No acute intracranial hemorrhage identified. Normal gray-white matter differentiation. No midline shift. Ventricles are normal in size and configuration.', 92.50, '{"regions": ["frontal_lobe", "parietal_lobe", "temporal_lobe"], "markers": []}', 'RadAI-NeuroDetect v2.1', 'completed', 1, 'Concur with AI findings. No acute abnormality.'),
('ANA-002', 2, 'Lesion Detection', 'Multiple periventricular and juxtacortical T2/FLAIR hyperintense lesions identified. Largest lesion measures 12mm in the right periventricular white matter. Two lesions show enhancement suggesting active demyelination.', 88.30, '{"regions": ["periventricular", "juxtacortical", "corpus_callosum"], "markers": [{"x": 145, "y": 230, "size": 12}, {"x": 198, "y": 180, "size": 8}]}', 'RadAI-NeuroDetect v2.1', 'completed', 1, 'Findings consistent with demyelinating disease. Recommend correlation with clinical history.'),
('ANA-003', 3, 'PE Detection', 'No pulmonary embolism identified. Main pulmonary artery is normal in caliber. No filling defects in the segmental or subsegmental pulmonary arteries. Incidental finding: 4mm ground-glass nodule in the right lower lobe.', 95.10, '{"regions": ["pulmonary_arteries", "right_lower_lobe"], "markers": [{"x": 310, "y": 275, "size": 4, "type": "nodule"}]}', 'RadAI-ChestAnalyzer v3.0', 'reviewed', 3, 'Agree no PE. GGN noted - recommend follow-up in 12 months per Fleischner.'),
('ANA-004', 4, 'Pneumonia Detection', 'Bilateral patchy airspace opacities predominantly in the lower lobes, more prominent on the right. Findings suggestive of bilateral lower lobe pneumonia. No pleural effusion. Cardiac silhouette is normal in size.', 87.60, '{"regions": ["right_lower_lobe", "left_lower_lobe"], "markers": [{"x": 280, "y": 350, "size": 45}, {"x": 120, "y": 340, "size": 30}]}', 'RadAI-ChestAnalyzer v3.0', 'completed', NULL, NULL),
('ANA-005', 5, 'Prostate Lesion Detection', 'PI-RADS 4 lesion identified in the left peripheral zone at mid-gland level, measuring 15mm. Restricted diffusion with corresponding low ADC values. Early enhancement on dynamic contrast sequences. No extracapsular extension.', 84.20, '{"regions": ["left_peripheral_zone", "mid_gland"], "markers": [{"x": 165, "y": 210, "size": 15, "pirads": 4}]}', 'RadAI-ProstateScreen v1.5', 'reviewed', 4, 'Agree with PI-RADS 4 assessment. Recommend targeted biopsy.'),
('ANA-006', 6, 'Breast Mass Detection', 'Hypoechoic mass identified at 2 o''clock position of the left breast, 5cm from nipple, measuring 18x12x14mm. Irregular margins with posterior acoustic shadowing. No axillary lymphadenopathy. BI-RADS assessment: 4B.', 91.40, '{"regions": ["left_breast_2_oclock"], "markers": [{"x": 200, "y": 185, "size": 18, "birads": "4B"}]}', 'RadAI-BreastDetect v2.0', 'completed', 5, 'Suspicious morphology. Recommend tissue sampling - core needle biopsy.'),
('ANA-007', 7, 'Spine Pathology Detection', 'L4-L5 broad-based disc herniation with left paracentral component causing moderate left lateral recess stenosis and impingement on the left L5 nerve root. Mild facet arthropathy at L4-L5 and L5-S1. No spinal canal stenosis.', 90.80, '{"regions": ["L4_L5_disc", "left_lateral_recess"], "markers": [{"x": 155, "y": 340, "size": 20, "type": "herniation"}]}', 'RadAI-SpineAnalyzer v1.8', 'reviewed', 2, 'Confirmed L4-L5 herniation with nerve impingement. Clinical correlation recommended.'),
('ANA-008', 8, 'Fetal Anatomy Assessment', 'Normal fetal anatomy survey. Estimated fetal weight 1150g (50th percentile). Normal amniotic fluid volume (AFI 14cm). Anterior placenta, grade 1 maturity. Fetal heart rate regular at 145 bpm. No structural anomalies identified.', 93.70, '{"regions": ["fetal_head", "fetal_spine", "fetal_heart", "placenta"], "markers": []}', 'RadAI-OBScreen v2.2', 'completed', 7, 'Normal 28-week anatomy. All measurements within normal limits.'),
('ANA-009', 9, 'Lung Nodule Detection', 'Previously identified 6mm solid nodule in the right upper lobe is stable compared to prior study (6 months ago). No new pulmonary nodules. No lymphadenopathy. No pleural effusion.', 96.20, '{"regions": ["right_upper_lobe"], "markers": [{"x": 275, "y": 120, "size": 6, "type": "solid_nodule", "stability": "stable"}]}', 'RadAI-LungScreen v3.1', 'reviewed', 3, 'Stable nodule. Can extend follow-up to 12 months per Lung-RADS 2.'),
('ANA-010', 10, 'MS Lesion Detection', 'Compared to prior study, two new T2/FLAIR hyperintense lesions identified: one in the left periventricular region (8mm) and one in the right cerebellar peduncle (6mm). Both enhance post-contrast. Total lesion burden has increased.', 89.50, '{"regions": ["left_periventricular", "right_cerebellar_peduncle"], "markers": [{"x": 120, "y": 200, "size": 8, "new": true}, {"x": 280, "y": 310, "size": 6, "new": true}]}', 'RadAI-NeuroDetect v2.1', 'completed', 11, 'New active lesions confirmed. Disease progression. Recommend clinical reassessment.'),
('ANA-011', 11, 'Aneurysm Measurement', 'Infrarenal abdominal aortic aneurysm measuring 5.2cm in maximum diameter (previously 4.8cm, 6 months ago). Growth rate approximately 0.8cm/year. No evidence of rupture or dissection. Mural thrombus present.', 94.80, '{"regions": ["infrarenal_aorta"], "markers": [{"x": 200, "y": 280, "size": 52, "type": "aneurysm", "growth": "0.8cm/yr"}]}', 'RadAI-VascularDetect v1.4', 'reviewed', 6, 'Growth rate exceeds threshold. Recommend vascular surgery consultation for repair.'),
('ANA-012', 12, 'ACL Assessment', 'Complete tear of the anterior cruciate ligament with associated bone marrow edema in the lateral femoral condyle and posterior tibial plateau (bone bruise pattern). Moderate joint effusion. Intact PCL, MCL, and LCL. Medial meniscus intact. Small lateral meniscus tear (posterior horn).', 91.20, '{"regions": ["ACL", "lateral_femoral_condyle", "lateral_meniscus"], "markers": [{"x": 180, "y": 250, "type": "ACL_tear"}, {"x": 210, "y": 290, "type": "bone_bruise"}, {"x": 195, "y": 310, "type": "meniscus_tear"}]}', 'RadAI-MSKDetect v2.0', 'reviewed', 2, 'Classic ACL tear with bone bruise pattern. Lateral meniscus tear also noted. Surgical planning recommended.'),
('ANA-013', 13, 'Pancreatic Mass Detection', 'Hypodense mass in the head of the pancreas measuring 3.2x2.8cm with associated pancreatic duct dilation (7mm). No vascular encasement of SMA or celiac axis. Two suspicious peripancreatic lymph nodes (largest 14mm). Mild intrahepatic biliary dilation.', 86.90, '{"regions": ["pancreatic_head", "pancreatic_duct", "peripancreatic_nodes"], "markers": [{"x": 230, "y": 265, "size": 32, "type": "mass"}, {"x": 260, "y": 250, "size": 14, "type": "lymph_node"}]}', 'RadAI-AbdominalDetect v2.5', 'completed', 4, 'Findings concerning for pancreatic adenocarcinoma. Appears resectable. Recommend EUS with FNA.'),
('ANA-014', 14, 'Thyroid Nodule Assessment', 'Dominant nodule in the right thyroid lobe measuring 22x15x18mm. Solid composition with microcalcifications and irregular margins. Increased vascularity on Doppler. TI-RADS score: TR5 (highly suspicious). Left lobe: 8mm benign-appearing cyst.', 90.30, '{"regions": ["right_thyroid_lobe"], "markers": [{"x": 175, "y": 195, "size": 22, "tirads": "TR5", "features": ["microcalcifications", "irregular_margins", "hypervascularity"]}]}', 'RadAI-ThyroidScreen v1.6', 'reviewed', 13, 'Highly suspicious nodule. FNA recommended per ACR TI-RADS guidelines.'),
('ANA-015', 15, 'Renal Stone Detection', '8mm obstructing calculus at the left ureterovesical junction with moderate left hydroureteronephrosis. Perinephric fat stranding present. No right-sided stones. Bladder is unremarkable. Appendix is normal.', 97.10, '{"regions": ["left_UVJ", "left_kidney"], "markers": [{"x": 145, "y": 380, "size": 8, "type": "calculus"}, {"x": 130, "y": 220, "type": "hydronephrosis"}]}', 'RadAI-URO-Detect v1.3', 'completed', 12, 'Obstructing stone confirmed. Urology referral recommended given size and location.'),
('ANA-016', 16, 'FDG Uptake Analysis', 'Multiple hypermetabolic lymph nodes identified: bilateral cervical, mediastinal, bilateral axillary, and bilateral inguinal. Largest node in the mediastinum (SUVmax 14.2). Splenic involvement with diffuse increased uptake (SUVmax 8.5). No skeletal lesions. Lugano stage III.', 88.70, '{"regions": ["cervical_nodes", "mediastinal_nodes", "axillary_nodes", "inguinal_nodes", "spleen"], "markers": [{"x": 200, "y": 150, "suv": 14.2, "type": "node"}, {"x": 180, "y": 280, "suv": 8.5, "type": "spleen"}]}', 'RadAI-PETAnalyzer v1.9', 'reviewed', 8, 'Widespread lymphadenopathy with splenic involvement. Consistent with stage III lymphoma. Recommend biopsy of most accessible node.');

-- Seed Prior Studies (16)
INSERT INTO prior_studies (study_id, patient_id, modality, body_part, study_date, diagnosis, findings, radiologist_name, institution, similarity_tags, study_notes, outcome, follow_up_required) VALUES
('STD-001', 1, 'CT', 'Head', '2025-06-15', 'Normal CT Head', 'No acute intracranial abnormality. Age-appropriate cerebral atrophy.', 'Dr. Sarah Mitchell', 'Massachusetts General Hospital', ARRAY['head', 'ct', 'normal', 'headache'], 'Baseline study for comparison', 'Resolved', false),
('STD-002', 2, 'MRI', 'Brain', '2025-08-20', 'New onset seizure - normal MRI', 'No structural abnormality identified. No enhancing lesions.', 'Dr. Aisha Mohammed', 'Brigham and Women''s Hospital', ARRAY['brain', 'mri', 'seizure', 'normal'], 'Initial workup was normal', 'Under monitoring', true),
('STD-003', 3, 'CT', 'Chest', '2025-06-03', 'COPD changes, no PE', 'Emphysematous changes bilateral upper lobes. No pulmonary embolism. Coronary artery calcifications noted.', 'Dr. Elena Rodriguez', 'Massachusetts General Hospital', ARRAY['chest', 'ct', 'copd', 'emphysema'], 'Known COPD patient', 'Stable disease', true),
('STD-004', 5, 'MRI', 'Prostate', '2025-06-05', 'PI-RADS 3 lesion', 'Indeterminate 10mm lesion in the left peripheral zone. PI-RADS 3. Recommend follow-up MRI in 6 months.', 'Dr. Michael Chang', 'Dana-Farber Cancer Institute', ARRAY['prostate', 'mri', 'pirads', 'lesion'], 'PSA was 5.2 at time of study', 'Progressed to PI-RADS 4', true),
('STD-005', 6, 'Ultrasound', 'Breast', '2025-06-06', 'BI-RADS 3 - probably benign', 'Small hypoechoic focus at 2 o''clock left breast, 8mm. Oval, circumscribed. BI-RADS 3.', 'Dr. Rebecca Foster', 'Massachusetts General Hospital', ARRAY['breast', 'ultrasound', 'mass', 'birads3'], '6-month follow-up recommended', 'Mass has grown - upgraded to BI-RADS 4B', true),
('STD-006', 7, 'MRI', 'Lumbar Spine', '2025-03-07', 'L4-L5 disc bulge', 'Mild broad-based disc bulge at L4-L5 without significant neural compression. Mild facet arthropathy.', 'Dr. James Park', 'Beth Israel Deaconess', ARRAY['spine', 'lumbar', 'mri', 'disc', 'bulge'], 'Conservative management attempted', 'Worsened - now herniation', true),
('STD-007', 9, 'CT', 'Chest', '2025-06-09', 'Stable lung nodule', '6mm solid nodule in the right upper lobe, stable compared to prior. Lung-RADS 2.', 'Dr. Catherine Nguyen', 'Massachusetts General Hospital', ARRAY['chest', 'ct', 'nodule', 'lung', 'screening'], 'Annual screening patient', 'Stable', true),
('STD-008', 10, 'MRI', 'Brain', '2025-04-10', 'Multiple sclerosis - stable', 'Known MS with multiple periventricular and juxtacortical lesions. No new or enhancing lesions compared to prior.', 'Dr. Sarah Mitchell', 'Brigham and Women''s Hospital', ARRAY['brain', 'mri', 'ms', 'demyelination', 'stable'], 'On current disease-modifying therapy', 'Was stable, now progressed', true),
('STD-009', 11, 'CT', 'Abdomen', '2025-06-11', 'AAA 4.8cm', 'Infrarenal abdominal aortic aneurysm measuring 4.8cm. Mural thrombus present. No evidence of rupture.', 'Dr. Anthony Russo', 'Massachusetts General Hospital', ARRAY['abdomen', 'ct', 'aaa', 'aneurysm', 'aorta'], 'Surveillance protocol', 'Growing - now 5.2cm', true),
('STD-010', 12, 'X-Ray', 'Knee', '2025-11-12', 'Knee joint effusion', 'Moderate right knee joint effusion. No fracture. Normal alignment.', 'Dr. Marcus Johnson', 'Newton-Wellesley Hospital', ARRAY['knee', 'xray', 'effusion', 'trauma'], 'Post-sports injury initial evaluation', 'ACL tear confirmed on MRI', true),
('STD-011', 13, 'CT', 'Abdomen', '2025-10-13', 'Pancreatic duct dilation', 'Mild pancreatic duct dilation (5mm). No discrete mass identified. Recommend MRCP or follow-up.', 'Dr. Michael Chang', 'Dana-Farber Cancer Institute', ARRAY['abdomen', 'ct', 'pancreas', 'duct_dilation'], 'Early finding before mass was evident', 'Mass now identified - 3.2cm', true),
('STD-012', 14, 'Ultrasound', 'Thyroid', '2025-05-14', 'Thyroid nodule - TI-RADS 4', 'Right thyroid lobe nodule 16mm. Solid, hypoechoic with some microcalcifications. TI-RADS 4.', 'Dr. Laura Kim', 'Massachusetts General Hospital', ARRAY['thyroid', 'ultrasound', 'nodule', 'tirads'], 'FNA was initially deferred due to patient preference', 'Nodule has grown to 22mm - now TR5', true),
('STD-013', 15, 'CT', 'Abdomen', '2025-01-15', 'Passed kidney stone', '3mm non-obstructing calculus in the left renal pelvis. No hydronephrosis.', 'Dr. Steven Clark', 'Beth Israel Deaconess', ARRAY['abdomen', 'ct', 'kidney', 'stone', 'renal'], 'History of recurrent stones', 'New obstructing stone at UVJ', true),
('STD-014', 16, 'CT', 'Chest', '2025-11-16', 'Mediastinal lymphadenopathy', 'Newly identified mediastinal and bilateral hilar lymphadenopathy. Largest node 2.5cm. Recommend PET/CT for further evaluation.', 'Dr. Elena Rodriguez', 'Massachusetts General Hospital', ARRAY['chest', 'ct', 'lymphadenopathy', 'mediastinal'], 'Led to PET/CT staging', 'Confirmed lymphoma on PET/CT', true),
('STD-015', 3, 'X-Ray', 'Chest', '2025-09-20', 'Hyperinflated lungs', 'Hyperinflated lungs consistent with COPD. No acute consolidation. Stable cardiomegaly.', 'Dr. Catherine Nguyen', 'Massachusetts General Hospital', ARRAY['chest', 'xray', 'copd', 'cardiomegaly'], 'Routine follow-up', 'Stable', false),
('STD-016', 4, 'X-Ray', 'Chest', '2025-10-15', 'Normal chest X-ray', 'Clear lungs bilaterally. Normal cardiac silhouette. No pleural effusion.', 'Dr. Daniel O''Brien', 'Cambridge Health Alliance', ARRAY['chest', 'xray', 'normal'], 'Baseline study', 'New symptoms developed', true);

-- Seed Reports (16)
INSERT INTO reports (report_id, image_id, patient_id, radiologist_id, report_type, clinical_history, technique, findings, impression, recommendations, ai_draft, final_report, status, compliance_check, signed_date) VALUES
('RPT-001', 1, 1, 1, 'CT Head', 'Acute headache, worst headache of life. No trauma.', 'Non-contrast CT of the head was performed with axial and coronal reformats.', 'No acute intracranial hemorrhage. No mass effect or midline shift. Ventricles and sulci are age-appropriate. Gray-white matter differentiation is preserved. Visualized paranasal sinuses and mastoid air cells are clear. Osseous structures are intact.', 'No acute intracranial abnormality.', 'Clinical correlation recommended. If symptoms persist, consider CTA or MRA to evaluate for vascular etiology.', 'AI-generated draft: No signs of hemorrhage or acute pathology detected on non-contrast CT head.', NULL, 'draft', false, NULL),
('RPT-002', 2, 2, 1, 'MRI Brain', 'New onset seizures. No prior history of epilepsy.', 'MRI of the brain was performed with and without IV gadolinium contrast. Sequences include T1, T2, FLAIR, DWI, and post-contrast T1.', 'Multiple periventricular and juxtacortical T2/FLAIR hyperintense lesions. Largest lesion measures 12mm in the right periventricular white matter. Two lesions demonstrate post-contrast enhancement. No restricted diffusion. No mass effect.', 'Findings are concerning for demyelinating disease, most likely multiple sclerosis. Active enhancing lesions suggest ongoing disease activity.', 'Recommend neurology consultation. Lumbar puncture for CSF analysis including oligoclonal bands. Follow-up MRI in 3 months.', 'AI draft: Multiple white matter lesions with enhancement pattern suggestive of MS.', 'FINAL REPORT: MRI Brain with and without contrast demonstrates multiple periventricular and juxtacortical T2/FLAIR hyperintense lesions with two actively enhancing lesions, findings highly suggestive of multiple sclerosis with active disease.', 'finalized', true, '2025-12-03 16:00:00'),
('RPT-003', 3, 3, 3, 'CT Chest PE Protocol', 'SOB, elevated D-dimer, COPD history.', 'CT angiography of the chest was performed with IV contrast using PE protocol.', 'No filling defects in the main, lobar, segmental, or subsegmental pulmonary arteries. Main pulmonary artery is normal in caliber. Emphysematous changes in bilateral upper lobes. Coronary artery calcifications. Incidental 4mm ground-glass nodule in the right lower lobe.', 'No pulmonary embolism. Known COPD changes. Incidental 4mm GGN in the right lower lobe.', 'Follow-up CT chest in 12 months for incidental ground-glass nodule per Fleischner Society guidelines. Continue COPD management.', 'AI draft: No PE detected. Incidental GGN noted in RLL requiring follow-up.', 'FINAL REPORT: No pulmonary embolism. Known emphysematous changes. Incidental 4mm ground-glass nodule in the right lower lobe - recommend 12-month follow-up CT per Fleischner guidelines.', 'finalized', true, '2025-12-04 11:30:00'),
('RPT-004', 4, 4, 10, 'Chest X-Ray', 'Persistent cough for 2 weeks. Low-grade fever.', 'PA and lateral chest radiographs were obtained.', 'Bilateral patchy airspace opacities in the lower lobes, more prominent on the right. No pleural effusion. Cardiac silhouette is normal in size. Mediastinal contours are unremarkable. No pneumothorax.', 'Bilateral lower lobe airspace disease consistent with pneumonia, more prominent on the right.', 'Clinical correlation. Consider follow-up chest X-ray in 4-6 weeks to document resolution. If symptoms worsen, consider CT chest.', 'AI draft: Bilateral lower lobe pneumonia pattern identified.', NULL, 'draft', false, NULL),
('RPT-005', 5, 5, 4, 'MRI Prostate', 'Elevated PSA (7.8). Prior PI-RADS 3 lesion 6 months ago.', 'Multiparametric MRI of the prostate was performed including T2W, DWI, ADC, and DCE sequences.', 'PI-RADS 4 lesion in the left peripheral zone at mid-gland level, measuring 15mm (previously 10mm). Restricted diffusion with low ADC values (650 mm2/s). Early enhancement on dynamic contrast. No extracapsular extension. Seminal vesicles are normal. No suspicious lymphadenopathy.', 'PI-RADS 4 lesion in the left peripheral zone, increased in size from prior study. Findings are suspicious for clinically significant prostate cancer.', 'Recommend MRI-targeted biopsy. Urology referral for biopsy planning. Consider MRI-TRUS fusion biopsy.', 'AI draft: Suspicious PI-RADS 4 prostate lesion with interval growth. Biopsy recommended.', 'FINAL REPORT: PI-RADS 4 lesion in the left peripheral zone measuring 15mm, increased from 10mm on prior study. Restricted diffusion and early enhancement are suspicious for clinically significant prostate cancer. MRI-targeted biopsy is recommended.', 'finalized', true, '2025-12-06 14:00:00'),
('RPT-006', 6, 6, 5, 'Breast Ultrasound', 'Palpable mass left breast. Mammogram showed BI-RADS 4 density.', 'Bilateral breast ultrasound was performed with high-frequency linear transducer.', 'Left breast: Hypoechoic mass at 2 o''clock position, 5cm from nipple, measuring 18x12x14mm. Irregular margins with posterior acoustic shadowing. No internal vascularity on color Doppler. Right breast: No suspicious findings. No axillary lymphadenopathy bilaterally.', 'Suspicious solid mass in the left breast, BI-RADS 4B. Features concerning for malignancy.', 'Core needle biopsy of the left breast mass is recommended. Refer to breast surgery for tissue sampling.', 'AI draft: BI-RADS 4B suspicious mass in left breast. Biopsy strongly recommended.', NULL, 'in_review', false, NULL),
('RPT-007', 7, 7, 2, 'MRI Lumbar Spine', 'Chronic low back pain with left leg radiculopathy. Failed conservative therapy.', 'MRI of the lumbar spine was performed without IV contrast. Sequences include sagittal T1, T2, and axial T2.', 'L4-L5: Broad-based disc herniation with left paracentral component measuring 8mm. Moderate left lateral recess stenosis with impingement on the left L5 nerve root. Mild facet arthropathy. L5-S1: Mild facet arthropathy, no significant disc herniation. Conus medullaris terminates at L1 level. No spinal canal stenosis.', 'L4-L5 disc herniation with left L5 nerve root impingement, likely accounting for the patient''s radiculopathy.', 'Neurosurgery or orthopedic spine consultation for surgical evaluation. Consider epidural steroid injection for symptom management.', 'AI draft: L4-L5 disc herniation with nerve root compression. Surgical consultation may be warranted.', 'FINAL REPORT: L4-L5 broad-based disc herniation with left paracentral component causing moderate left lateral recess stenosis and L5 nerve root impingement. Findings correlate with clinical radiculopathy. Surgical consultation recommended.', 'finalized', true, '2025-12-08 10:15:00'),
('RPT-008', 8, 8, 7, 'OB Ultrasound', '28-week pregnancy. Gestational diabetes. Routine anatomy scan.', 'Transabdominal obstetric ultrasound was performed.', 'Single viable intrauterine pregnancy. Fetal heart rate 145 bpm, regular. EFW 1150g (50th percentile). BPD, HC, AC, and FL all within normal limits for gestational age. Normal amniotic fluid (AFI 14cm). Anterior placenta, grade 1 maturity, well clear of the cervical os. Normal fetal anatomy survey including brain, spine, heart (4-chamber view), kidneys, and extremities.', 'Normal 28-week obstetric ultrasound. Appropriate fetal growth and anatomy.', 'Continue routine prenatal care. Follow-up growth ultrasound in 4 weeks given gestational diabetes. Monitor for macrosomia.', 'AI draft: Normal fetal anatomy and growth at 28 weeks. No abnormalities detected.', 'FINAL REPORT: Normal 28-week anatomy scan with appropriate fetal growth. EFW at 50th percentile. Normal amniotic fluid and placentation. Recommend growth follow-up in 4 weeks given GDM.', 'finalized', true, '2025-12-09 12:30:00'),
('RPT-009', 9, 9, 3, 'CT Chest Low-Dose', 'Lung nodule surveillance. Former smoker, 30 pack-years.', 'Low-dose CT of the chest was performed without IV contrast.', '6mm solid nodule in the right upper lobe is unchanged compared to prior study from 6 months ago. No new pulmonary nodules. No lymphadenopathy. No pleural effusion. Emphysematous changes in the upper lobes.', 'Stable 6mm right upper lobe nodule. Lung-RADS 2 (benign appearance).', 'Follow-up low-dose CT in 12 months. Can consider annual screening if continued stability.', 'AI draft: Stable RUL nodule. No new findings. Recommend continued surveillance.', 'FINAL REPORT: Stable 6mm solid nodule in the right upper lobe compared to 6-month prior. Lung-RADS 2. Recommend 12-month follow-up low-dose CT.', 'finalized', true, '2025-12-10 09:45:00'),
('RPT-010', 10, 10, 11, 'MRI Brain MS Protocol', 'MS follow-up. New neurological symptoms - right-sided weakness.', 'MRI of the brain was performed with and without IV gadolinium contrast using MS protocol.', 'Compared to prior study from 8 months ago, two new T2/FLAIR hyperintense lesions are identified: 8mm left periventricular lesion and 6mm right cerebellar peduncle lesion. Both demonstrate post-contrast enhancement indicating active inflammation. Previously seen lesions are stable. Total lesion burden has increased.', 'Active multiple sclerosis with two new enhancing lesions indicating disease progression on current therapy.', 'Urgent neurology consultation for therapy modification. Consider escalation to higher-efficacy disease-modifying therapy. Repeat MRI in 3 months to assess treatment response.', 'AI draft: Disease progression with new active MS lesions. Therapy change recommended.', NULL, 'in_review', false, NULL),
('RPT-011', 11, 11, 6, 'CT Abdomen', 'AAA surveillance. Known 4.8cm aneurysm.', 'CT angiography of the abdomen and pelvis was performed with IV contrast.', 'Infrarenal AAA now measures 5.2cm in maximum diameter (previously 4.8cm, 6 months ago). Growth rate approximately 0.8cm/year. Mural thrombus is present. Aneurysm extends to the aortic bifurcation. No evidence of rupture, dissection, or retroperitoneal hematoma. Bilateral common iliac arteries are normal in caliber.', 'Enlarging infrarenal AAA measuring 5.2cm with growth rate exceeding 1cm/year threshold. No evidence of rupture.', 'Urgent vascular surgery consultation for repair planning given size >5cm and rapid growth rate. Consider EVAR vs open repair.', 'AI draft: AAA has grown to 5.2cm. Exceeds intervention threshold. Surgical referral needed.', 'FINAL REPORT: Infrarenal AAA has enlarged from 4.8cm to 5.2cm over 6 months (growth rate 0.8cm/year). Size exceeds 5cm threshold and growth rate exceeds guidelines. Urgent vascular surgery consultation for repair planning recommended.', 'finalized', true, '2025-12-12 15:00:00'),
('RPT-012', 12, 12, 2, 'MRI Knee', 'Right knee injury during soccer. Acute onset swelling and instability.', 'MRI of the right knee was performed without IV contrast.', 'Complete tear of the ACL with wavy, discontinuous fibers and abnormal signal. Bone marrow edema in the lateral femoral condyle and posterior tibial plateau consistent with pivot-shift bone bruise pattern. Moderate joint effusion. Small tear of the posterior horn of the lateral meniscus. PCL, MCL, and LCL are intact. Articular cartilage is preserved.', 'Complete ACL tear with classic bone bruise pattern. Lateral meniscus posterior horn tear. Moderate effusion.', 'Orthopedic surgery consultation for ACL reconstruction planning. Consider concomitant meniscal repair. Prehabilitation program recommended.', 'AI draft: ACL tear with associated bone bruises and lateral meniscus tear. Surgical repair recommended.', 'FINAL REPORT: Complete ACL tear with pivot-shift bone bruise pattern and small lateral meniscus posterior horn tear. Recommend orthopedic surgery consultation for ACL reconstruction with possible meniscal repair.', 'finalized', true, '2025-12-13 11:45:00'),
('RPT-013', 13, 13, 4, 'CT Abdomen Pancreas Protocol', 'Weight loss, jaundice, new-onset diabetes. Prior CT showed duct dilation.', 'CT of the abdomen was performed with IV contrast using pancreas protocol (arterial and venous phases).', 'Hypodense mass in the head of the pancreas measuring 3.2x2.8cm. Main pancreatic duct dilated to 7mm. Two peripancreatic lymph nodes measuring up to 14mm. Mild intrahepatic biliary dilation. No liver metastases. No ascites. SMA and celiac axis are patent without encasement. SMV/portal vein confluence is patent.', 'Pancreatic head mass with ductal dilation and suspicious lymphadenopathy. Findings are concerning for pancreatic adenocarcinoma. Appears surgically resectable based on vascular assessment.', 'EUS with FNA for tissue diagnosis. Multidisciplinary tumor board discussion. CA 19-9 level. Consider neoadjuvant therapy evaluation.', 'AI draft: Pancreatic head mass suspicious for adenocarcinoma. Appears resectable. Tissue diagnosis needed.', NULL, 'draft', false, NULL),
('RPT-014', 14, 14, 13, 'Thyroid Ultrasound', 'Thyroid nodule follow-up. Hashimoto thyroiditis on levothyroxine.', 'Ultrasound of the thyroid was performed with high-frequency linear transducer and color Doppler.', 'Right lobe: Dominant solid hypoechoic nodule measuring 22x15x18mm (previously 16mm, 10 months ago). Microcalcifications present. Irregular margins. Increased vascularity on Doppler. TI-RADS score: TR5. Left lobe: 8mm simple cyst, benign. No suspicious cervical lymphadenopathy.', 'Highly suspicious right thyroid nodule (ACR TI-RADS TR5) with interval growth and concerning features.', 'FNA biopsy is strongly recommended per ACR TI-RADS guidelines. Refer to endocrinology for biopsy coordination.', 'AI draft: TR5 thyroid nodule with growth and suspicious features. FNA urgently needed.', NULL, 'in_review', false, NULL),
('RPT-015', 15, 15, 12, 'CT Abdomen Renal Stone Protocol', 'Acute left flank pain. History of recurrent kidney stones.', 'Non-contrast CT of the abdomen and pelvis was performed using renal stone protocol.', '8mm dense calculus at the left ureterovesical junction. Moderate left hydroureteronephrosis with perinephric fat stranding. Left ureter dilated to 9mm. No right-sided stones. Right kidney is normal. Bladder is unremarkable. Appendix is normal. No free fluid.', 'Obstructing 8mm left UVJ stone with moderate hydroureteronephrosis.', 'Urology consultation given stone size >6mm and obstructive features. Consider ureteroscopy with laser lithotripsy. Medical expulsive therapy may be attempted but likelihood of spontaneous passage is low.', 'AI draft: 8mm obstructing UVJ stone. Likely requires intervention given size.', 'FINAL REPORT: 8mm obstructing calculus at the left ureterovesical junction with moderate hydroureteronephrosis. Urology consultation recommended as spontaneous passage is unlikely given stone size.', 'finalized', true, '2025-12-16 13:20:00'),
('RPT-016', 16, 16, 8, 'PET/CT Whole Body', 'Newly diagnosed lymphoma. Staging workup.', 'Whole body PET/CT was performed following IV administration of 12 mCi FDG. Blood glucose 95 mg/dL at time of injection.', 'Hypermetabolic lymphadenopathy: Bilateral cervical (SUVmax 10.2), mediastinal (SUVmax 14.2), bilateral axillary (SUVmax 9.8), and bilateral inguinal (SUVmax 8.1). Splenic involvement with diffuse increased uptake (SUVmax 8.5). No suspicious skeletal lesions. No hepatic involvement. No pulmonary parenchymal disease.', 'Extensive hypermetabolic lymphadenopathy above and below the diaphragm with splenic involvement. Lugano classification: Stage III.', 'Biopsy of most accessible lymph node for histologic subtyping. Oncology referral for treatment planning. Bone marrow biopsy to complete staging. Baseline cardiac function assessment prior to chemotherapy.', 'AI draft: Stage III lymphoma with widespread nodal and splenic involvement. Treatment planning needed.', 'FINAL REPORT: Extensive FDG-avid lymphadenopathy involving cervical, mediastinal, axillary, and inguinal stations with splenic involvement. Lugano Stage III. Recommend tissue biopsy, bone marrow biopsy, and oncology referral for treatment initiation.', 'finalized', true, '2025-12-17 16:30:00');
